[project]
name = "rexnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
    "torch>=2.10.0",
    "transformers>=5.2.0",
]
